### Feature Engineering

In [1]:
import pandas as pd
import sys
sys.path.insert(0, '/10 A KAI 2/Week6/Credit_Scoring/')

In [2]:
from Script.Feature_engi import Feature_Engineering

In [3]:
df = pd.read_csv('../Data/data.csv')

In [4]:
fut_eng = Feature_Engineering(df)

##### Remove unneccery columns which not have contribution for the credit scoring and only one values like CountryCode

In [5]:
attrib=['BatchId',  'SubscriptionId', 'CurrencyCode', 'CountryCode', 'ProductId', 'ProviderId']
fut_eng.remove_some_cols(attrib)

,TransactionId,AccountId,CustomerId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult
0,TransactionId_76871,AccountId_3957,CustomerId_4406,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0
1,TransactionId_73770,AccountId_4841,CustomerId_4406,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0
2,TransactionId_26203,AccountId_4229,CustomerId_4683,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0
3,TransactionId_380,AccountId_648,CustomerId_988,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0
4,TransactionId_28195,AccountId_4841,CustomerId_988,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0
...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,AccountId_4841,CustomerId_3078,financial_services,ChannelId_2,-1000.0,1000,2019-02-13T09:54:09Z,2,0
95658,TransactionId_91597,AccountId_3439,CustomerId_3874,airtime,ChannelId_3,1000.0,1000,2019-02-13T09:54:25Z,2,0
95659,TransactionId_82501,AccountId_4841,CustomerId_3874,financial_services,ChannelId_2,-20.0,20,2019-02-13T09:54:35Z,2,0
95660,TransactionId_136354,AccountId_1346,CustomerId_1709,tv,ChannelId_3,3000.0,3000,2019-02-13T10:01:10Z,2,0
95661,TransactionId_35670,AccountId_4841,CustomerId_1709,financial_services,ChannelId_2,-60.0,60,2019-02-13T10:01:28Z,2,0

#### Label encoding for column ProductCategory, and ChannelId

In [6]:
column = ['ChannelId', 'ProductCategory']
df1 = fut_eng.onehotencoding_selected_col(column)

One-hot encoding completed for columns: ['ChannelId', 'ProductCategory']

### Aggregate Credit and Debit transaction amount in the customer label and i did feature enginering the col i generate with decription describe below 
1. **Total Credit Amount**: Summed the values in the Credit column to determine the total credit transactions for each customer.
2. **Total Debit Amount**: Summed the values in the Debit column to determine the total debit transactions for each customer.
3. **Average Transaction Amount**: Calculated the mean of the Value column, which represents the average transaction value for each customer.
4.  **Transaction Count**: Counted the number of transactions per CustomerId using the TransactionId column.
5.  **Total Unique Account Count**: Counted the unique accounts associated with each customer using the AccountId column.
6.  **Standard Deviation of Transaction Amount**: Computed the standard deviation of the Amount column to assess the variability of transaction amounts. The ddof=0 parameter ensures a population standard deviation is calculated, and if there are fewer than two entries, NaN is replaced with zero. 
7. **Fraud Result**:This metric indicates the presence of fraud-related transactions. A value of 1 signifies that at least one transaction was flagged as fraudulent. 
8. **Channel-Specific Transaction Counts** : The sums for each specified channel (ChannelId_1, ChannelId_2, ChannelId_3, ChannelId_5) highlight the volume of transactions conducted through different channels. This can inform channel effectiveness and customer preferences. 
9. **Distinct Product Categories:** The count of unique product categories associated with transactions, which can reveal customer preferences and product diversity.

In [7]:
df2 = fut_eng.feature_engineering_transaction()

In [8]:
fut_eng.outlier_percentage()

,Column,outlier_percentage
ProductCategory_utility_bill,ProductCategory_utility_bill,15.098878
ProductCategory_data_bundles,ProductCategory_data_bundles,13.548904
ProductCategory_airtime,ProductCategory_airtime,11.998931
Transaction_Count,Transaction_Count,11.972207
ProductCategory_financial_services,ProductCategory_financial_services,11.838589
Total_Transaction_amount,Total_Transaction_amount,11.785142
Total_Credit_Amount,Total_Credit_Amount,11.758418
ChannelId_ChannelId_3,ChannelId_ChannelId_3,11.437734
ChannelId_ChannelId_2,ChannelId_ChannelId_2,11.143773
ProductCategory_tv,ProductCategory_tv,9.540353
Total_Debit_Amount,Total_Debit_Amount,9.273116
Average_Transaction_Amount,Average_Transaction_Amount,9.005879
Standard_Deviation_Transaction_Amount,Standard_Deviation_Transaction_Amount,7.856761
ChannelId_ChannelId_5,ChannelId_ChannelId_5,5.237841
ChannelId_ChannelId_1,ChannelId_ChannelId_1,2.458578
ProductCategory_ticket,ProductCategory_ticket,1.950828
ProductCategory_movies,ProductCategory_movies,1.790486
FraudResult,FraudResult,1.443079
ProductCategory_transport,ProductCategory_transport,0.614645
ProductCategory_other,ProductCategory_other,0.026724
Total_Unique_Account_Count,Total_Unique_Account_Count,0.000000

#### Treat outlier by using Capping method which is use upper and lower limites to manages the outliers values. this method is help to maintain all data becaus we have small number of data record.

In [9]:
fut_eng.cap_outliers()

,CustomerId,Total_Credit_Amount,Total_Debit_Amount,Total_Transaction_amount,Average_Transaction_Amount,Transaction_Count,Total_Unique_Account_Count,FraudResult,ChannelId_ChannelId_1,ChannelId_ChannelId_2,...,ProductCategory_airtime,ProductCategory_data_bundles,ProductCategory_financial_services,ProductCategory_movies,ProductCategory_other,ProductCategory_ticket,ProductCategory_transport,ProductCategory_tv,ProductCategory_utility_bill,Standard_Deviation_Transaction_Amount
0,CustomerId_1,0.000,10000.0,10000,10000.000000,1,1,0,0,1.0,...,1,0,0.0,0,0,0,0,0,0,0.000000
1,CustomerId_10,0.000,10000.0,10000,10000.000000,1,1,0,0,1.0,...,1,0,0.0,0,0,0,0,0,0,0.000000
2,CustomerId_1001,25200.000,5200.0,30400,6080.000000,5,2,0,0,2.0,...,2,0,3.0,0,0,0,0,0,0,5866.515150
3,CustomerId_1002,4500.000,275.0,4775,434.090909,11,2,0,0,6.0,...,5,0,6.0,0,0,0,0,0,0,534.414795
4,CustomerId_1003,26000.000,6000.0,32000,5333.333333,6,3,0,0,2.0,...,3,0,3.0,0,0,0,0,0,0,5505.048188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3737,CustomerId_992,26000.000,6000.0,32000,5333.333333,6,3,0,0,2.0,...,3,0,3.0,0,0,0,0,0,0,5557.777334
3738,CustomerId_993,26000.000,6000.0,32000,6400.000000,5,3,0,0,2.0,...,2,0,3.0,0,0,0,0,0,0,6033.241252
3739,CustomerId_994,216974.375,27500.0,245400,6079.970297,47,2,0,0,17.5,...,21,0,23.5,0,0,0,0,0,0,14727.203940
3740,CustomerId_996,145000.000,6000.0,151000,8882.352941,17,3,0,0,2.0,...,2,0,15.0,0,0,0,0,0,0,4300.961508
3741,CustomerId_998,131500.000,27500.0,163000,7409.090909,22,3,0,0,8.0,...,14,0,8.0,0,0,0,0,0,0,6619.374268

In [10]:
fut_eng.outlier_percentage()

,Column,outlier_percentage
Total_Credit_Amount,Total_Credit_Amount,0.0
ProductCategory_airtime,ProductCategory_airtime,0.0
ProductCategory_utility_bill,ProductCategory_utility_bill,0.0
ProductCategory_tv,ProductCategory_tv,0.0
ProductCategory_transport,ProductCategory_transport,0.0
ProductCategory_ticket,ProductCategory_ticket,0.0
ProductCategory_other,ProductCategory_other,0.0
ProductCategory_movies,ProductCategory_movies,0.0
ProductCategory_financial_services,ProductCategory_financial_services,0.0
ProductCategory_data_bundles,ProductCategory_data_bundles,0.0
ChannelId_ChannelId_5,ChannelId_ChannelId_5,0.0
Total_Debit_Amount,Total_Debit_Amount,0.0
ChannelId_ChannelId_3,ChannelId_ChannelId_3,0.0
ChannelId_ChannelId_2,ChannelId_ChannelId_2,0.0
ChannelId_ChannelId_1,ChannelId_ChannelId_1,0.0
FraudResult,FraudResult,0.0
Total_Unique_Account_Count,Total_Unique_Account_Count,0.0
Transaction_Count,Transaction_Count,0.0
Average_Transaction_Amount,Average_Transaction_Amount,0.0
Total_Transaction_amount,Total_Transaction_amount,0.0
Standard_Deviation_Transaction_Amount,Standard_Deviation_Transaction_Amount,0.0

##### The above result shows the aggrigation by customer. totally we have 3742 customer.

#### Scale continues columns

In [11]:
fut_eng.numeric_feature_scaling()

      Total_Credit_Amount  Total_Debit_Amount  Total_Transaction_amount  \
0               -0.826640            0.377591                 -0.728235
1               -0.826640            0.377591                 -0.728235
2               -0.481362           -0.155651                 -0.481001
3               -0.764983           -0.702779                 -0.791558
4               -0.470401           -0.066777                 -0.461611
...                   ...                 ...                       ...
3737            -0.470401           -0.066777                 -0.461611
3738            -0.470401           -0.066777                 -0.461611
3739             2.146229            2.321701                  2.124643
3740             1.160074           -0.066777                  0.980583
3741             0.975104            2.321701                  1.126014

      Average_Transaction_Amount  Transaction_Count  \
0                       1.043121          -0.839070
1                       1.043121          -0.839070
2                       0.200178          -0.582472
3                      -1.013899          -0.197574
4                       0.039617          -0.518322
...                          ...                ...
3737                    0.039617          -0.518322
3738                    0.268989          -0.582472
3739                    0.200171           2.111810
3740                    0.802786           0.187323
3741                    0.485981           0.508071

      Total_Unique_Account_Count  FraudResult  ChannelId_ChannelId_1  \
0                      -1.356587          0.0                    0.0
1                      -1.356587          0.0                    0.0
2                      -0.223474          0.0                    0.0
3                      -0.223474          0.0                    0.0
4                       0.909640          0.0                    0.0
...                          ...          ...                    ...
3737                    0.909640          0.0                    0.0
3738                    0.909640          0.0                    0.0
3739                   -0.223474          0.0                    0.0
3740                    0.909640          0.0                    0.0
3741                    0.909640          0.0                    0.0

      ChannelId_ChannelId_2  ChannelId_ChannelId_3  ...  \
0                 -0.674625              -0.884094  ...
1                 -0.674625              -0.884094  ...
2                 -0.501010              -0.590607  ...
3                  0.193449              -0.394949  ...
4                 -0.501010              -0.492778  ...
...                     ...                    ...  ...
3737              -0.501010              -0.492778  ...
3738              -0.501010              -0.590607  ...
3739               2.190018               2.148601  ...
3740              -0.501010               0.583339  ...
3741               0.540679               0.485510  ...

      ProductCategory_airtime  ProductCategory_data_bundles  \
0                   -0.709758                           0.0
1                   -0.709758                           0.0
2                   -0.568906                           0.0
3                   -0.146348                           0.0
4                   -0.428053                           0.0
...                       ...                           ...
3737                -0.428053                           0.0
3738                -0.568906                           0.0
3739                 2.107292                           0.0
3740                -0.568906                           0.0
3741                 1.121324                           0.0

      ProductCategory_financial_services  ProductCategory_movies  \
0                              -0.909351                     0.0
1                              -0.909351                     0.0
2                              -0.521104                     0.0
3                              -0.132857                     0.0
4                              -0.521104                     0.0
...                                  ...                     ...
3737                           -0.521104                     0.0
3738                           -0.521104                     0.0
3739                            2.131917                     0.0
3740                            1.031884                     0.0
3741                            0.125975                     0.0

      ProductCategory_other  ProductCategory_ticket  \
0                       0.0                     0.0
1                       0.0                     0.0
2                       0.0                     0.0
3                       0.0                     0.0
4                       0.0                     0.0
...                     ...                     ...
3737                    0.0                     0.0
3738                    0.0                     0.0
3739                    0.0                     0.0
3740                    0.0                     0.0
3741                    0.0                     0.0

      ProductCategory_transport  ProductCategory_tv  \
0                           0.0                 0.0
1                           0.0                 0.0
2                           0.0                 0.0
3                           0.0                 0.0
4                           0.0                 0.0
...                         ...                 ...
3737                        0.0                 0.0
3738                        0.0                 0.0
3739                        0.0                 0.0
3740                        0.0                 0.0
3741                        0.0                 0.0

      ProductCategory_utility_bill  Standard_Deviation_Transaction_Amount
0                              0.0                              -0.960924
1                              0.0                              -0.960924
2                              0.0                               0.363661
3                              0.0                              -0.840260
4                              0.0                               0.282046
...                            ...                                    ...
3737                           0.0                               0.293952
3738                           0.0                               0.401305
3739                           0.0                               2.364292
3740                           0.0                               0.010178
3741                           0.0                               0.533647

[3742 rows x 21 columns]

,CustomerId,Total_Credit_Amount,Total_Debit_Amount,Total_Transaction_amount,Average_Transaction_Amount,Transaction_Count,Total_Unique_Account_Count,FraudResult,ChannelId_ChannelId_1,ChannelId_ChannelId_2,...,ProductCategory_airtime,ProductCategory_data_bundles,ProductCategory_financial_services,ProductCategory_movies,ProductCategory_other,ProductCategory_ticket,ProductCategory_transport,ProductCategory_tv,ProductCategory_utility_bill,Standard_Deviation_Transaction_Amount
0,CustomerId_1,-0.826640,0.377591,-0.728235,1.043121,-0.839070,-1.356587,0.0,0.0,-0.674625,...,-0.709758,0.0,-0.909351,0.0,0.0,0.0,0.0,0.0,0.0,-0.960924
1,CustomerId_10,-0.826640,0.377591,-0.728235,1.043121,-0.839070,-1.356587,0.0,0.0,-0.674625,...,-0.709758,0.0,-0.909351,0.0,0.0,0.0,0.0,0.0,0.0,-0.960924
2,CustomerId_1001,-0.481362,-0.155651,-0.481001,0.200178,-0.582472,-0.223474,0.0,0.0,-0.501010,...,-0.568906,0.0,-0.521104,0.0,0.0,0.0,0.0,0.0,0.0,0.363661
3,CustomerId_1002,-0.764983,-0.702779,-0.791558,-1.013899,-0.197574,-0.223474,0.0,0.0,0.193449,...,-0.146348,0.0,-0.132857,0.0,0.0,0.0,0.0,0.0,0.0,-0.840260
4,CustomerId_1003,-0.470401,-0.066777,-0.461611,0.039617,-0.518322,0.909640,0.0,0.0,-0.501010,...,-0.428053,0.0,-0.521104,0.0,0.0,0.0,0.0,0.0,0.0,0.282046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3737,CustomerId_992,-0.470401,-0.066777,-0.461611,0.039617,-0.518322,0.909640,0.0,0.0,-0.501010,...,-0.428053,0.0,-0.521104,0.0,0.0,0.0,0.0,0.0,0.0,0.293952
3738,CustomerId_993,-0.470401,-0.066777,-0.461611,0.268989,-0.582472,0.909640,0.0,0.0,-0.501010,...,-0.568906,0.0,-0.521104,0.0,0.0,0.0,0.0,0.0,0.0,0.401305
3739,CustomerId_994,2.146229,2.321701,2.124643,0.200171,2.111810,-0.223474,0.0,0.0,2.190018,...,2.107292,0.0,2.131917,0.0,0.0,0.0,0.0,0.0,0.0,2.364292
3740,CustomerId_996,1.160074,-0.066777,0.980583,0.802786,0.187323,0.909640,0.0,0.0,-0.501010,...,-0.568906,0.0,1.031884,0.0,0.0,0.0,0.0,0.0,0.0,0.010178
3741,CustomerId_998,0.975104,2.321701,1.126014,0.485981,0.508071,0.909640,0.0,0.0,0.540679,...,1.121324,0.0,0.125975,0.0,0.0,0.0,0.0,0.0,0.0,0.533647

In [12]:
# Save the data farther use 
df2.to_csv('../Data/data_v1.csv')

#### Extract Transaction day, year,  month and Hour fron trsnsaction date

In [14]:
fut_eng.extract_transaction_features()

,TransactionId,AccountId,CustomerId,ProviderId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult,Transaction_Hour,Transaction_Day,Transaction_Month,Transaction_Year
0,TransactionId_76871,AccountId_3957,CustomerId_4406,ProviderId_6,airtime,ChannelId_3,1000.0,1000,2018-11-15 02:18:49+00:00,2,0,2,15,11,2018
1,TransactionId_73770,AccountId_4841,CustomerId_4406,ProviderId_4,financial_services,ChannelId_2,-20.0,20,2018-11-15 02:19:08+00:00,2,0,2,15,11,2018
2,TransactionId_26203,AccountId_4229,CustomerId_4683,ProviderId_6,airtime,ChannelId_3,500.0,500,2018-11-15 02:44:21+00:00,2,0,2,15,11,2018
3,TransactionId_380,AccountId_648,CustomerId_988,ProviderId_1,utility_bill,ChannelId_3,20000.0,21800,2018-11-15 03:32:55+00:00,2,0,3,15,11,2018
4,TransactionId_28195,AccountId_4841,CustomerId_988,ProviderId_4,financial_services,ChannelId_2,-644.0,644,2018-11-15 03:34:21+00:00,2,0,3,15,11,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,AccountId_4841,CustomerId_3078,ProviderId_4,financial_services,ChannelId_2,-1000.0,1000,2019-02-13 09:54:09+00:00,2,0,9,13,2,2019
95658,TransactionId_91597,AccountId_3439,CustomerId_3874,ProviderId_6,airtime,ChannelId_3,1000.0,1000,2019-02-13 09:54:25+00:00,2,0,9,13,2,2019
95659,TransactionId_82501,AccountId_4841,CustomerId_3874,ProviderId_4,financial_services,ChannelId_2,-20.0,20,2019-02-13 09:54:35+00:00,2,0,9,13,2,2019
95660,TransactionId_136354,AccountId_1346,CustomerId_1709,ProviderId_6,tv,ChannelId_3,3000.0,3000,2019-02-13 10:01:10+00:00,2,0,10,13,2,2019
95661,TransactionId_35670,AccountId_4841,CustomerId_1709,ProviderId_4,financial_services,ChannelId_2,-60.0,60,2019-02-13 10:01:28+00:00,2,0,10,13,2,2019